import "../globals.css"
import "bootstrap/dist/css/bootstrap.min.css";
import NewNavbar from "../NewNavbar";
import { Roboto, Work_Sans } from "next/font/google";
import NewFooter from "../NewFooter";
import AosLoader from "../AosLoader";

const workSans = Work_Sans({
  subsets: ["latin"],
  variable: "--font-work-sans",
});

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
         <head>
        <meta name="description" content="Customization and You provides digital marketing, web design, video editing, and branding services." />
      </head>
      <body className={`${workSans.variable} ${roboto.variable}`}>
        <AosLoader/>
      <NewNavbar/>
        {children}
      <NewFooter/>
        </body>
    </html>
  )
}
