import "../../globals.css"
import "bootstrap/dist/css/bootstrap.min.css";
import { Roboto, Work_Sans } from "next/font/google";
import Sidebar from "./Sidebar";

const workSans = Work_Sans({
  subsets: ["latin"],
  variable: "--font-work-sans",
});

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata = {
  title: 'Admin Panel',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
      <div className={`${workSans.variable} ${roboto.variable}`}>
        <div className="container">
        <div className="row">
          <div className="col-lg-2 col-md-2 col-sm-12">
        <Sidebar/>
        </div>
         <div className="col-lg-10 col-md-10 col-sm-12">
        {children}
        </div>
        </div>
        </div>
        </div>
  )
}
